// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2G-ddjiq0dS1XjYDB0x6tRt-3nGtKnyQ',
    appId: '1:868062974093:web:26eb9177d05dd581a852c4',
    messagingSenderId: '868062974093',
    projectId: 'bookshare-96dc3',
    authDomain: 'bookshare-96dc3.firebaseapp.com',
    storageBucket: 'bookshare-96dc3.appspot.com',
    measurementId: 'G-G0EEWF4T89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWdNNQ-4bBQMGZp6fmZajeXI_2ACABHI',
    appId: '1:868062974093:android:9fb80b8c7dc3e007a852c4',
    messagingSenderId: '868062974093',
    projectId: 'bookshare-96dc3',
    storageBucket: 'bookshare-96dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjg460pDEGIww4rJprK659m3jc-MFn2o0',
    appId: '1:868062974093:ios:002f4408546d7703a852c4',
    messagingSenderId: '868062974093',
    projectId: 'bookshare-96dc3',
    storageBucket: 'bookshare-96dc3.appspot.com',
    androidClientId: '868062974093-5bunvnqi3m06qnnql9rjqk3pc2bbarlb.apps.googleusercontent.com',
    iosClientId: '868062974093-6uejf1gl8hrg5u2jse5n1hsdrlm81qhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjg460pDEGIww4rJprK659m3jc-MFn2o0',
    appId: '1:868062974093:ios:002f4408546d7703a852c4',
    messagingSenderId: '868062974093',
    projectId: 'bookshare-96dc3',
    storageBucket: 'bookshare-96dc3.appspot.com',
    androidClientId: '868062974093-5bunvnqi3m06qnnql9rjqk3pc2bbarlb.apps.googleusercontent.com',
    iosClientId: '868062974093-6uejf1gl8hrg5u2jse5n1hsdrlm81qhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2G-ddjiq0dS1XjYDB0x6tRt-3nGtKnyQ',
    appId: '1:868062974093:web:f7b354dbaaf7e0d5a852c4',
    messagingSenderId: '868062974093',
    projectId: 'bookshare-96dc3',
    authDomain: 'bookshare-96dc3.firebaseapp.com',
    storageBucket: 'bookshare-96dc3.appspot.com',
    measurementId: 'G-PCXEXFB46Z',
  );

}